version: '3' 
services:
  web:
    image: playmaker
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: rails s -b 0.0.0.0
    env_file:
     - .env/development/database
     - .env/development/web
  redis:
    image: redis
  database:
   image: postgres
   env_file:
     - .env/development/database
   volumes:
     - db_data:/var/lib/postgresql/data
volumes:
  db_data: